# Generated by Django 2.2.5 on 2019-09-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiparametricreading',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
