# Generated by Django 2.2.5 on 2019-09-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalis', '0002_auto_20190921_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiparametricreading',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
