# Generated by Django 2.2.5 on 2019-09-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalis', '0003_auto_20190921_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiparametricreading',
            name='oxygen_saturation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
